{{- if .Values.ingress.enabled }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ .Values.Name | default .Chart.Name }}-https
  labels:
    app: {{ .Values.Name | default .Chart.Name }}
    name: {{ .Values.Name | default .Chart.Name }}-https
    chart: {{ .Values.Name | default .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}   
  annotations:
    haproxy.org/ingress.class: "haproxy"
    ingress.kubernetes.io/service-upstream: "true"
    ingress.kubernetes.io/ssl-redirect: "false"
    ingress.kubernetes.io/timeout-http-request: "{{ .Values.ingressHaproxyTimeout | default "1m" }}"
    ingress.kubernetes.io/timeout-server: "{{ .Values.ingressHaproxyTimeout | default "1m" }}"
    ingress.kubernetes.io/proxy-body-size: '{{ .Values.ingressHaproxyMaxBodySize | default "1m" }}'	
spec:
  host: {{ .Values.Host }}
  #path: /{{ .Values.IngressPath }}
  to:
    kind: Service
    name: {{ .Values.Name | default .Chart.Name }}
    weight: 100
  wildcardPolicy: None 	    
  #tls: 
  #  termination: "passthrough"
{{- end }}