apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.Name | default .Chart.Name }}
  annotations:
    service.alpha.openshift.io/serving-cert-secret-name: "{{ .Values.Name | default .Chart.Name }}-cert"
  labels:
    app: {{ .Values.Name | default .Chart.Name }}
    name: {{ .Values.Name | default .Chart.Name }}-service
    chart: {{ .Values.Name | default .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }} 
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
    name: {{ .Values.Name | default .Chart.Name }}
  selector:
    app: {{ .Values.Name | default .Chart.Name }}
    release: {{ .Release.Name }}
